var word_pairs_json = {
    "words": [
        "Heart Beat", "Frying Pan", "Pillow Case", "Front Porch", "Gift Wrap",
        "Tooth Paste", "True Love", "Coffee Mug", "Dinner Table", "Bed Sheet",
        "Trash Can", "Washing Machine", "Dining Room", "Kitchen Sink", "Shower Head",
        "Living Room", "Vacuum Cleaner", "Wine Glass", "Cutting Board", "Dish Towel",
        "Paper Towel", "Light Bulb", "Ceiling Fan", "Trash Bag", "Rain Coat",
        "Cell Phone", "Door Bell", "Milk Carton", "Wall Clock", "Book Shelf",
        "Tooth Brush", "Lunch Box", "Parking Lot", "Salt Shaker", "Tea Pot",
        "Ice Cream", "Dish Soap", "Night Stand", "Hair Brush", "Tooth Floss",
        "Game Room", "Pizza Box", "Wine Bottle", "Desk Lamp", "Smoke Alarm",
        "Water Bottle", "Dust Pan", "Flower Pot", "Fire Place", "Spin Cycle",
        "Laundry Bag", "Trash Bin", "Fire Alarm", "Soap Dish", "Bread Crumb",
        "Coffee Pot", "Shoe Lace", "Rain Gear", "Dish Rack", "Beer Mug",
        "Chair Lift", "Food Truck", "Mail Box", "Hair Dryer", "Bike Rack",
        "Road Map", "School Bus", "Wind Shield", "Seat Belt", "Wash Cloth",
        "Bath Robe", "Tooth Pick", "Soap Bubble", "Paper Clip", "Shoe Horn",
        "Bread Knife", "Butter Knife", "Dining Chair", "Ping Pong", "Tennis Ball",
        "Salad Bowl", "Fruit Bowl", "Candy Bar", "Burger King", "Pizza Slice",
        "Milk Shake", "Fish Tank", "Bird Cage", "Dog House", "Cat Bed",
        "Door Knob", "Key Chain", "Drum Stick", "Tooth Nerve", "Dinner Plate",
        "Lunch Tray", "Bed Frame", "Table Lamp", "Coat Rack", "Oven Mitt",
        "Egg Timer", "Can Opener", "Dish Gloves", "Tea Kettle", "Coffee Maker",
        "Spice Rack", "Kitchen Table", "Soap Dispenser", "Trash Pickup", "Window Shade",
        "Bike Helmet", "Sun Glasses", "Rain Jacket", "Snow Shoes", "Shoe Shine",
        "Tooth Decay", "Love Story", "Dinner Guest", "Wine Cork", "Towel Rack",
        "Shoe Box", "Tooth Crown", "Magic Wand", "Paper Weight", "Desk Chair",
        "Coffee Bean", "Water Tank", "Book Mark", "Shoe Store", "Rain Storm",
        "Food Chain", "Tea Spoon", "Door Step", "Nail File", "Hair Spray",
        "Tooth Root", "Wine Rack", "Bread Box", "Trash Truck", "Soap Opera",
        "Boat Dock", "Snow Ball", "Bed Spread", "Shoe Rack", "Pizza Cutter",
        "Milk Jug", "Dish Rag", "Fire Truck", "Desk Top", "Lunch Bag",
        "Cat Walk", "Bike Ride", "Wall Paper", "Salt Mine", "Tea Room",
        "Egg Roll", "Paper Bag", "Trash Talk", "Wine List", "Shoe Polish",
        "Coffee Shop", "Water Fall", "Book Case", "Food Court", "Rain Drop",
        "Tooth Fairy", "Love Song", "Dinner Plate", "Wine Glass", "Towel Set",
        "Shoe Heel", "Tooth Brush", "Magic Hat", "Paper Clip", "Desk Lamp",
        "Hair Band", "Tea Bag", "Door Frame", "Nail Polish", "Rain Cover",
        "Food Truck", "Spoon Rest", "Trash Lid", "Wine Opener", "Soap Dish",
        "Boat Ride", "Snow Cone", "Bed Skirt", "Shoe Lace", "Pizza Pan",
        "Milk Cow", "Dish Soap", "Fire Exit", "Desk Pad", "Lunch Money",
        "Cat Food", "Bike Path", "Wall Art", "Salt Flat", "Tea Light",
        "Egg Shell", "Paper Cup", "Trash Bin", "Wine Cork", "Shoe Brush",
        "Coffee Mug", "Water Pipe", "Book Mark", "Food Stall", "Rain Gear",
        "Tooth Decay", "Love Note", "Dinner Napkin", "Wine Bottle", "Towel Rack",
        "Shoe Box", "Tooth Paste", "Magic Wand", "Paper Tray", "Desk Clock",
        "Hair Clip", "Tea Pot", "Door Stop", "Nail Buffer", "Rain Shield",
        "Food Stamp", "Spoon Set", "Trash Bag", "Wine Glass", "Soap Bar",
        "Boat Sail", "Snow Plow", "Bed Pillow", "Shoe Polish", "Pizza Stone",
        "Milk Shake", "Dish Rack", "Fire Alarm", "Desk Drawer", "Lunch Pail",
        "Cat Litter", "Bike Lane", "Wall Decor", "Salt Water", "Tea Towel",
        "Egg Whisk", "Paper Plate", "Trash Can", "Wine Cellar", "Shoe Spray",
        "Coffee Pot", "Water Tower", "Book Stand", "Food Bank", "Rain Boots",
        "Tooth Brush", "Love Letter", "Dinner Fork", "Wine Opener", "Towel Hook",
        "Shoe Shine", "Tooth Paste", "Magic Ring", "Paper Clip", "Desk Blotter",
        "Hair Spray", "Tea Cup", "Door Lock", "Nail Glue", "Rain Hat",
        "Food Scale", "Spoon Feed", "Trash Heap", "Wine List", "Soap Opera",
        "Boat House", "Snow Storm", "Bed Cover", "Shoe Rack", "Pizza Knife",
        "Milk Carton", "Dish Gloves", "Fire Escape", "Desk Pad", "Lunch Kit",
        "Cat Nap", "Bike Stand", "Wall Paint", "Salt Cellar", "Tea Kettle",
        "Egg Carton", "Paper Towel", "Trash Lid", "Wine Decanter", "Shoe Tree",
        "Coffee Maker", "Water Bottle", "Book Shelf", "Food Wagon", "Rain Coat",
        "Tooth Floss", "Love Poem", "Dinner Plate", "Wine Cork", "Towel Warmer",
        "Shoe Horn", "Tooth Crown", "Magic Trick", "Paper Tray", "Desk Lamp",
        "Hair Tie", "Tea Strainer", "Door Knob", "Nail Kit", "Rain Jacket",
        "Food Truck", "Spoon Holder", "Trash Pickup", "Wine Cooler", "Soap Dish",
        "Boat Rope", "Snow Globe", "Bed Skirt", "Shoe Brush", "Pizza Paddle",
        "Milk Jug", "Dish Soap", "Fire Truck", "Desk Clock", "Lunch Money",
        "Cat Tree", "Bike Lock", "Wall Sticker", "Salt Shaker", "Tea Room",
        "Egg Timer", "Paper Bag", "Trash Bin", "Wine Glass", "Shoe Polish",
        "Coffee Beans", "Water Jug", "Book Cover", "Food Stand", "Rain Shield",
        "Tooth Pick", "Love Song", "Dinner Napkin", "Wine Bottle", "Towel Rack",
        "Shoe Box", "Tooth Fairy", "Magic Wand", "Paper Weight", "Desk Pad",
        "Hair Net", "Tea Spoon", "Door Frame", "Nail File", "Rain Boots",
        "Food Chain", "Spoon Rest", "Trash Talk", "Wine Opener", "Soap Bar",
        "Boat Dock", "Snow Plow", "Bed Spread", "Shoe Lace", "Pizza Cutter",
        "Milk Shake", "Dish Rag", "Fire Alarm", "Desk Top", "Lunch Bag",
        "Cat Walk", "Bike Ride", "Wall Paper", "Salt Mine", "Tea Light",
        "Egg Roll", "Paper Cup", "Trash Heap", "Wine List", "Shoe Spray",
        "Coffee Shop", "Water Tank", "Book Shelf", "Food Court", "Rain Coat",
        "Tooth Root", "Love Story", "Dinner Guest", "Wine Decanter", "Towel Set",
        "Shoe Heel", "Tooth Brush", "Magic Hat", "Paper Clip", "Desk Lamp",
        "Hair Band", "Tea Kettle", "Door Stop", "Nail Polish", "Rain Cover",
        "Food Stall", "Spoon Set", "Trash Lid", "Wine Cork", "Soap Opera",
        "Boat Sail", "Snow Cone", "Bed Pillow", "Shoe Polish", "Pizza Stone",
        "Milk Carton", "Dish Rack", "Fire Escape", "Desk Drawer", "Lunch Pail",
        "Cat Litter", "Bike Lane", "Wall Decor", "Salt Water", "Tea Towel",
        "Egg Whisk", "Paper Plate", "Trash Can", "Wine Cellar", "Shoe Tree",
        "Coffee Pot", "Water Tower", "Book Stand", "Food Bank", "Rain Boots",
        "Tooth Decay", "Love Note", "Dinner Fork", "Wine Opener", "Towel Hook",
        "Shoe Shine", "Tooth Paste", "Magic Ring", "Paper Tray", "Desk Blotter",
        "Hair Spray", "Tea Cup", "Door Lock", "Nail Glue", "Rain Hat",
        "Food Scale", "Spoon Feed", "Trash Heap", "Wine List", "Soap Dish",
        "Boat House", "Snow Storm", "Bed Cover", "Shoe Rack", "Pizza Knife",
        "Milk Jug", "Dish Gloves", "Fire Truck", "Desk Pad", "Lunch Kit",
        "Cat Nap", "Bike Stand", "Wall Paint", "Salt Cellar", "Tea Kettle",
        "Egg Carton", "Paper Towel", "Trash Lid", "Wine Decanter", "Shoe Brush",
        "Coffee Maker", "Water Bottle", "Book Shelf", "Food Wagon", "Rain Coat",
        "Tooth Floss", "Love Poem", "Dinner Plate", "Wine Cork", "Towel Warmer",
        "Shoe Horn", "Tooth Crown", "Magic Trick", "Paper Tray", "Desk Lamp",
        "Hair Tie", "Tea Strainer", "Door Knob", "Nail Kit", "Rain Jacket",
        "Food Truck", "Spoon Holder", "Trash Pickup", "Wine Cooler", "Soap Opera",
        "Boat Rope", "Snow Globe", "Bed Skirt", "Shoe Brush", "Pizza Paddle",
        "Milk Shake", "Dish Soap", "Fire Alarm", "Desk Clock", "Lunch Money",
        "Cat Tree", "Bike Lock", "Wall Sticker", "Salt Shaker", "Tea Room"
    ]
}


var word_pairs_json = {
    "words": [
        "Heart Beat", "Frying Pan", "Pillow Case", "Front Porch", "Gift Wrap",
        "Tooth Paste", "True Love", "Coffee Mug", "Dinner Table", "Bed Sheet",
        "Trash Can", "Washing Machine", "Dining Room", "Kitchen Sink", "Shower Head"]
}

export { word_pairs_json };